apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java-microservice
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: java-microservice
    spec:
      containers:
      - name: microservice
        image: stevesloka/java-microservice:0.0.2
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8443
          protocol: TCP