apiVersion: v1
kind: Service
metadata:
  name: java-microservice
spec:
  type: NodePort
  ports:
  - name: java-microservice
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    name: java-microservice